// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkp6SBi2vgWKK8CkLmBHWw0nw5TvGanI8',
    appId: '1:116867349223:web:a76c57cd7be9bcf72c4042',
    messagingSenderId: '116867349223',
    projectId: 'test-a6ad2',
    authDomain: 'test-a6ad2.firebaseapp.com',
    storageBucket: 'test-a6ad2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv-U6esl0QPFgWTHTe7XGG7smUUh_it4o',
    appId: '1:116867349223:android:31eebc6ae91ee8012c4042',
    messagingSenderId: '116867349223',
    projectId: 'test-a6ad2',
    storageBucket: 'test-a6ad2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrLmKJZOwHBCtQnEy_ygZu3BHCX4P9uCs',
    appId: '1:116867349223:ios:028565b50aaa6b152c4042',
    messagingSenderId: '116867349223',
    projectId: 'test-a6ad2',
    storageBucket: 'test-a6ad2.appspot.com',
    iosClientId: '116867349223-tf2a3c0menb3iaupl70hu212e9pbj7ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.testGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrLmKJZOwHBCtQnEy_ygZu3BHCX4P9uCs',
    appId: '1:116867349223:ios:f719dce2216ba8db2c4042',
    messagingSenderId: '116867349223',
    projectId: 'test-a6ad2',
    storageBucket: 'test-a6ad2.appspot.com',
    iosClientId: '116867349223-86kukj0fi4cg742hrskhbcjl0pq09ec2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testGpt.RunnerTests',
  );
}
